/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rrc_cg_config.proto */

#ifndef PROTOBUF_C_rrc_5fcg_5fconfig_2eproto__INCLUDED
#define PROTOBUF_C_rrc_5fcg_5fconfig_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "rrc_common_types.pb-c.h"

typedef struct _Uenibstreamprotobuf__CGConfig Uenibstreamprotobuf__CGConfig;
typedef struct _Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1;
typedef struct _Uenibstreamprotobuf__CGConfigIEs Uenibstreamprotobuf__CGConfigIEs;
typedef struct _Uenibstreamprotobuf__ConfigRestrictModReqSCG Uenibstreamprotobuf__ConfigRestrictModReqSCG;
typedef struct _Uenibstreamprotobuf__BandCombinationInfoSN Uenibstreamprotobuf__BandCombinationInfoSN;
typedef struct _Uenibstreamprotobuf__FRInfoList Uenibstreamprotobuf__FRInfoList;
typedef struct _Uenibstreamprotobuf__FRInfo Uenibstreamprotobuf__FRInfo;
typedef struct _Uenibstreamprotobuf__FRType Uenibstreamprotobuf__FRType;
typedef struct _Uenibstreamprotobuf__CandidateServingFreqListNR Uenibstreamprotobuf__CandidateServingFreqListNR;
typedef struct _Uenibstreamprotobuf__CGConfigV1540IEs Uenibstreamprotobuf__CGConfigV1540IEs;
typedef struct _Uenibstreamprotobuf__ReportCGIRequest Uenibstreamprotobuf__ReportCGIRequest;
typedef struct _Uenibstreamprotobuf__RequestedCellInfo Uenibstreamprotobuf__RequestedCellInfo;
typedef struct _Uenibstreamprotobuf__PHTypeListSCG Uenibstreamprotobuf__PHTypeListSCG;
typedef struct _Uenibstreamprotobuf__PHInfoSCG Uenibstreamprotobuf__PHInfoSCG;
typedef struct _Uenibstreamprotobuf__PHUplinkCarrierSCG Uenibstreamprotobuf__PHUplinkCarrierSCG;
typedef struct _Uenibstreamprotobuf__MeasConfigSN Uenibstreamprotobuf__MeasConfigSN;


/* --- enums --- */

typedef enum _Uenibstreamprotobuf__FRType__Value {
  UENIBSTREAMPROTOBUF__FR__TYPE__VALUE__protobuf_unspecified = 0,
  UENIBSTREAMPROTOBUF__FR__TYPE__VALUE__fr1 = 1,
  UENIBSTREAMPROTOBUF__FR__TYPE__VALUE__fr2 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__FR__TYPE__VALUE)
} Uenibstreamprotobuf__FRType__Value;
typedef enum _Uenibstreamprotobuf__PHUplinkCarrierSCG__PHType1or3 {
  UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__PH__TYPE1OR3__protobuf_unspecified = 0,
  UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__PH__TYPE1OR3__type1 = 1,
  UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__PH__TYPE1OR3__type3 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__PH__TYPE1OR3)
} Uenibstreamprotobuf__PHUplinkCarrierSCG__PHType1or3;

/* --- messages --- */

typedef enum {
  UENIBSTREAMPROTOBUF__CG__CONFIG__CRITICAL_EXTENSIONS__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__CG__CONFIG__CRITICAL_EXTENSIONS_CRITICAL_EXTENSIONS_CHOICE1 = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__CG__CONFIG__CRITICAL_EXTENSIONS)
} Uenibstreamprotobuf__CGConfig__CriticalExtensionsCase;

struct  _Uenibstreamprotobuf__CGConfig
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__CGConfig__CriticalExtensionsCase critical_extensions_case;
  union {
    Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 *criticalextensionschoice1;
  };
};
#define UENIBSTREAMPROTOBUF__CG__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__cg__config__descriptor) \
    , UENIBSTREAMPROTOBUF__CG__CONFIG__CRITICAL_EXTENSIONS__NOT_SET, {0} }


typedef enum {
  UENIBSTREAMPROTOBUF__CG__CONFIG_CRITICAL_EXTENSIONS_CHOICE1__C1__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__CG__CONFIG_CRITICAL_EXTENSIONS_CHOICE1__C1_PROTOCOL_IES = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__CG__CONFIG_CRITICAL_EXTENSIONS_CHOICE1__C1)
} Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1__C1Case;

struct  _Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1__C1Case c1_case;
  union {
    Uenibstreamprotobuf__CGConfigIEs *protocolies;
  };
};
#define UENIBSTREAMPROTOBUF__CG__CONFIG_CRITICAL_EXTENSIONS_CHOICE1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__cg__config_critical_extensions_choice1__descriptor) \
    , UENIBSTREAMPROTOBUF__CG__CONFIG_CRITICAL_EXTENSIONS_CHOICE1__C1__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__CGConfigIEs
{
  ProtobufCMessage base;
  Google__Protobuf__StringValue *scg_cellgroupconfig;
  Uenibstreamprotobuf__RadioBearerConfig *scg_rb_config;
  Uenibstreamprotobuf__ConfigRestrictModReqSCG *configrestrictmodreq;
  Uenibstreamprotobuf__DRXInfo *drx_infoscg;
  Uenibstreamprotobuf__MeasResultList2NR *candidatecellinfolistsn;
  Uenibstreamprotobuf__MeasConfigSN *measconfigsn;
  Uenibstreamprotobuf__BandCombinationInfoSN *selectedbandcombinationnr;
  Uenibstreamprotobuf__FRInfoList *fr_infolistscg;
  Uenibstreamprotobuf__CandidateServingFreqListNR *candidateservingfreqlistnr;
  Uenibstreamprotobuf__CGConfigV1540IEs *noncriticalextension;
};
#define UENIBSTREAMPROTOBUF__CG__CONFIG__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__cg__config__ies__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__ConfigRestrictModReqSCG
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__BandCombinationInfoSN *requestedbc_mrdc;
  Google__Protobuf__Int32Value *requestedp_maxfr1;
};
#define UENIBSTREAMPROTOBUF__CONFIG_RESTRICT_MOD_REQ_SCG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__config_restrict_mod_req_scg__descriptor) \
    , NULL, NULL }


struct  _Uenibstreamprotobuf__BandCombinationInfoSN
{
  ProtobufCMessage base;
  uint32_t bandcombinationindex;
  uint32_t requestedfeaturesets;
};
#define UENIBSTREAMPROTOBUF__BAND_COMBINATION_INFO_SN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__band_combination_info_sn__descriptor) \
    , 0, 0 }


struct  _Uenibstreamprotobuf__FRInfoList
{
  ProtobufCMessage base;
  size_t n_items;
  Uenibstreamprotobuf__FRInfo **items;
};
#define UENIBSTREAMPROTOBUF__FR__INFO_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__fr__info_list__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__FRInfo
{
  ProtobufCMessage base;
  uint32_t servcellindex;
  Uenibstreamprotobuf__FRType *fr_type;
};
#define UENIBSTREAMPROTOBUF__FR__INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__fr__info__descriptor) \
    , 0, NULL }


struct  _Uenibstreamprotobuf__FRType
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__FRType__Value value;
};
#define UENIBSTREAMPROTOBUF__FR__TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__fr__type__descriptor) \
    , UENIBSTREAMPROTOBUF__FR__TYPE__VALUE__protobuf_unspecified }


struct  _Uenibstreamprotobuf__CandidateServingFreqListNR
{
  ProtobufCMessage base;
  size_t n_items;
  uint32_t *items;
};
#define UENIBSTREAMPROTOBUF__CANDIDATE_SERVING_FREQ_LIST_NR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__candidate_serving_freq_list_nr__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__CGConfigV1540IEs
{
  ProtobufCMessage base;
  Google__Protobuf__UInt32Value *pscellfrequency;
  Uenibstreamprotobuf__ReportCGIRequest *reportcgi_request;
  Uenibstreamprotobuf__PHTypeListSCG *ph_infoscg;
};
#define UENIBSTREAMPROTOBUF__CG__CONFIG_V1540__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__cg__config_v1540__ies__descriptor) \
    , NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__ReportCGIRequest
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__RequestedCellInfo *requestedcellinfo;
};
#define UENIBSTREAMPROTOBUF__REPORT_CGI__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__report_cgi__request__descriptor) \
    , NULL }


struct  _Uenibstreamprotobuf__RequestedCellInfo
{
  ProtobufCMessage base;
  uint32_t ssbfrequency;
  uint32_t cellforwhichtoreportcgi;
};
#define UENIBSTREAMPROTOBUF__REQUESTED_CELL_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__requested_cell_info__descriptor) \
    , 0, 0 }


struct  _Uenibstreamprotobuf__PHTypeListSCG
{
  ProtobufCMessage base;
  size_t n_items;
  Uenibstreamprotobuf__PHInfoSCG **items;
};
#define UENIBSTREAMPROTOBUF__PH__TYPE_LIST_SCG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__ph__type_list_scg__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__PHInfoSCG
{
  ProtobufCMessage base;
  uint32_t servcellindex;
  Uenibstreamprotobuf__PHUplinkCarrierSCG *ph_uplink;
  Uenibstreamprotobuf__PHUplinkCarrierSCG *ph_supplementaryuplink;
};
#define UENIBSTREAMPROTOBUF__PH__INFO_SCG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__ph__info_scg__descriptor) \
    , 0, NULL, NULL }


struct  _Uenibstreamprotobuf__PHUplinkCarrierSCG
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__PHUplinkCarrierSCG__PHType1or3 ph_type1or3;
};
#define UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__ph__uplink_carrier_scg__descriptor) \
    , UENIBSTREAMPROTOBUF__PH__UPLINK_CARRIER_SCG__PH__TYPE1OR3__protobuf_unspecified }


struct  _Uenibstreamprotobuf__MeasConfigSN
{
  ProtobufCMessage base;
  size_t n_measuredfrequenciessn;
  Uenibstreamprotobuf__NRFreqInfo **measuredfrequenciessn;
};
#define UENIBSTREAMPROTOBUF__MEAS_CONFIG_SN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__meas_config_sn__descriptor) \
    , 0,NULL }


/* Uenibstreamprotobuf__CGConfig methods */
void   uenibstreamprotobuf__cg__config__init
                     (Uenibstreamprotobuf__CGConfig         *message);
size_t uenibstreamprotobuf__cg__config__get_packed_size
                     (const Uenibstreamprotobuf__CGConfig   *message);
size_t uenibstreamprotobuf__cg__config__pack
                     (const Uenibstreamprotobuf__CGConfig   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__cg__config__pack_to_buffer
                     (const Uenibstreamprotobuf__CGConfig   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__CGConfig *
       uenibstreamprotobuf__cg__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__cg__config__free_unpacked
                     (Uenibstreamprotobuf__CGConfig *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 methods */
void   uenibstreamprotobuf__cg__config_critical_extensions_choice1__init
                     (Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1         *message);
size_t uenibstreamprotobuf__cg__config_critical_extensions_choice1__get_packed_size
                     (const Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1   *message);
size_t uenibstreamprotobuf__cg__config_critical_extensions_choice1__pack
                     (const Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__cg__config_critical_extensions_choice1__pack_to_buffer
                     (const Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 *
       uenibstreamprotobuf__cg__config_critical_extensions_choice1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__cg__config_critical_extensions_choice1__free_unpacked
                     (Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__CGConfigIEs methods */
void   uenibstreamprotobuf__cg__config__ies__init
                     (Uenibstreamprotobuf__CGConfigIEs         *message);
size_t uenibstreamprotobuf__cg__config__ies__get_packed_size
                     (const Uenibstreamprotobuf__CGConfigIEs   *message);
size_t uenibstreamprotobuf__cg__config__ies__pack
                     (const Uenibstreamprotobuf__CGConfigIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__cg__config__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__CGConfigIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__CGConfigIEs *
       uenibstreamprotobuf__cg__config__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__cg__config__ies__free_unpacked
                     (Uenibstreamprotobuf__CGConfigIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ConfigRestrictModReqSCG methods */
void   uenibstreamprotobuf__config_restrict_mod_req_scg__init
                     (Uenibstreamprotobuf__ConfigRestrictModReqSCG         *message);
size_t uenibstreamprotobuf__config_restrict_mod_req_scg__get_packed_size
                     (const Uenibstreamprotobuf__ConfigRestrictModReqSCG   *message);
size_t uenibstreamprotobuf__config_restrict_mod_req_scg__pack
                     (const Uenibstreamprotobuf__ConfigRestrictModReqSCG   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__config_restrict_mod_req_scg__pack_to_buffer
                     (const Uenibstreamprotobuf__ConfigRestrictModReqSCG   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ConfigRestrictModReqSCG *
       uenibstreamprotobuf__config_restrict_mod_req_scg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__config_restrict_mod_req_scg__free_unpacked
                     (Uenibstreamprotobuf__ConfigRestrictModReqSCG *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__BandCombinationInfoSN methods */
void   uenibstreamprotobuf__band_combination_info_sn__init
                     (Uenibstreamprotobuf__BandCombinationInfoSN         *message);
size_t uenibstreamprotobuf__band_combination_info_sn__get_packed_size
                     (const Uenibstreamprotobuf__BandCombinationInfoSN   *message);
size_t uenibstreamprotobuf__band_combination_info_sn__pack
                     (const Uenibstreamprotobuf__BandCombinationInfoSN   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__band_combination_info_sn__pack_to_buffer
                     (const Uenibstreamprotobuf__BandCombinationInfoSN   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__BandCombinationInfoSN *
       uenibstreamprotobuf__band_combination_info_sn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__band_combination_info_sn__free_unpacked
                     (Uenibstreamprotobuf__BandCombinationInfoSN *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__FRInfoList methods */
void   uenibstreamprotobuf__fr__info_list__init
                     (Uenibstreamprotobuf__FRInfoList         *message);
size_t uenibstreamprotobuf__fr__info_list__get_packed_size
                     (const Uenibstreamprotobuf__FRInfoList   *message);
size_t uenibstreamprotobuf__fr__info_list__pack
                     (const Uenibstreamprotobuf__FRInfoList   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__fr__info_list__pack_to_buffer
                     (const Uenibstreamprotobuf__FRInfoList   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__FRInfoList *
       uenibstreamprotobuf__fr__info_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__fr__info_list__free_unpacked
                     (Uenibstreamprotobuf__FRInfoList *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__FRInfo methods */
void   uenibstreamprotobuf__fr__info__init
                     (Uenibstreamprotobuf__FRInfo         *message);
size_t uenibstreamprotobuf__fr__info__get_packed_size
                     (const Uenibstreamprotobuf__FRInfo   *message);
size_t uenibstreamprotobuf__fr__info__pack
                     (const Uenibstreamprotobuf__FRInfo   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__fr__info__pack_to_buffer
                     (const Uenibstreamprotobuf__FRInfo   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__FRInfo *
       uenibstreamprotobuf__fr__info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__fr__info__free_unpacked
                     (Uenibstreamprotobuf__FRInfo *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__FRType methods */
void   uenibstreamprotobuf__fr__type__init
                     (Uenibstreamprotobuf__FRType         *message);
size_t uenibstreamprotobuf__fr__type__get_packed_size
                     (const Uenibstreamprotobuf__FRType   *message);
size_t uenibstreamprotobuf__fr__type__pack
                     (const Uenibstreamprotobuf__FRType   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__fr__type__pack_to_buffer
                     (const Uenibstreamprotobuf__FRType   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__FRType *
       uenibstreamprotobuf__fr__type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__fr__type__free_unpacked
                     (Uenibstreamprotobuf__FRType *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__CandidateServingFreqListNR methods */
void   uenibstreamprotobuf__candidate_serving_freq_list_nr__init
                     (Uenibstreamprotobuf__CandidateServingFreqListNR         *message);
size_t uenibstreamprotobuf__candidate_serving_freq_list_nr__get_packed_size
                     (const Uenibstreamprotobuf__CandidateServingFreqListNR   *message);
size_t uenibstreamprotobuf__candidate_serving_freq_list_nr__pack
                     (const Uenibstreamprotobuf__CandidateServingFreqListNR   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__candidate_serving_freq_list_nr__pack_to_buffer
                     (const Uenibstreamprotobuf__CandidateServingFreqListNR   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__CandidateServingFreqListNR *
       uenibstreamprotobuf__candidate_serving_freq_list_nr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__candidate_serving_freq_list_nr__free_unpacked
                     (Uenibstreamprotobuf__CandidateServingFreqListNR *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__CGConfigV1540IEs methods */
void   uenibstreamprotobuf__cg__config_v1540__ies__init
                     (Uenibstreamprotobuf__CGConfigV1540IEs         *message);
size_t uenibstreamprotobuf__cg__config_v1540__ies__get_packed_size
                     (const Uenibstreamprotobuf__CGConfigV1540IEs   *message);
size_t uenibstreamprotobuf__cg__config_v1540__ies__pack
                     (const Uenibstreamprotobuf__CGConfigV1540IEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__cg__config_v1540__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__CGConfigV1540IEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__CGConfigV1540IEs *
       uenibstreamprotobuf__cg__config_v1540__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__cg__config_v1540__ies__free_unpacked
                     (Uenibstreamprotobuf__CGConfigV1540IEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ReportCGIRequest methods */
void   uenibstreamprotobuf__report_cgi__request__init
                     (Uenibstreamprotobuf__ReportCGIRequest         *message);
size_t uenibstreamprotobuf__report_cgi__request__get_packed_size
                     (const Uenibstreamprotobuf__ReportCGIRequest   *message);
size_t uenibstreamprotobuf__report_cgi__request__pack
                     (const Uenibstreamprotobuf__ReportCGIRequest   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__report_cgi__request__pack_to_buffer
                     (const Uenibstreamprotobuf__ReportCGIRequest   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ReportCGIRequest *
       uenibstreamprotobuf__report_cgi__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__report_cgi__request__free_unpacked
                     (Uenibstreamprotobuf__ReportCGIRequest *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RequestedCellInfo methods */
void   uenibstreamprotobuf__requested_cell_info__init
                     (Uenibstreamprotobuf__RequestedCellInfo         *message);
size_t uenibstreamprotobuf__requested_cell_info__get_packed_size
                     (const Uenibstreamprotobuf__RequestedCellInfo   *message);
size_t uenibstreamprotobuf__requested_cell_info__pack
                     (const Uenibstreamprotobuf__RequestedCellInfo   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__requested_cell_info__pack_to_buffer
                     (const Uenibstreamprotobuf__RequestedCellInfo   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RequestedCellInfo *
       uenibstreamprotobuf__requested_cell_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__requested_cell_info__free_unpacked
                     (Uenibstreamprotobuf__RequestedCellInfo *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__PHTypeListSCG methods */
void   uenibstreamprotobuf__ph__type_list_scg__init
                     (Uenibstreamprotobuf__PHTypeListSCG         *message);
size_t uenibstreamprotobuf__ph__type_list_scg__get_packed_size
                     (const Uenibstreamprotobuf__PHTypeListSCG   *message);
size_t uenibstreamprotobuf__ph__type_list_scg__pack
                     (const Uenibstreamprotobuf__PHTypeListSCG   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__ph__type_list_scg__pack_to_buffer
                     (const Uenibstreamprotobuf__PHTypeListSCG   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__PHTypeListSCG *
       uenibstreamprotobuf__ph__type_list_scg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__ph__type_list_scg__free_unpacked
                     (Uenibstreamprotobuf__PHTypeListSCG *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__PHInfoSCG methods */
void   uenibstreamprotobuf__ph__info_scg__init
                     (Uenibstreamprotobuf__PHInfoSCG         *message);
size_t uenibstreamprotobuf__ph__info_scg__get_packed_size
                     (const Uenibstreamprotobuf__PHInfoSCG   *message);
size_t uenibstreamprotobuf__ph__info_scg__pack
                     (const Uenibstreamprotobuf__PHInfoSCG   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__ph__info_scg__pack_to_buffer
                     (const Uenibstreamprotobuf__PHInfoSCG   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__PHInfoSCG *
       uenibstreamprotobuf__ph__info_scg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__ph__info_scg__free_unpacked
                     (Uenibstreamprotobuf__PHInfoSCG *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__PHUplinkCarrierSCG methods */
void   uenibstreamprotobuf__ph__uplink_carrier_scg__init
                     (Uenibstreamprotobuf__PHUplinkCarrierSCG         *message);
size_t uenibstreamprotobuf__ph__uplink_carrier_scg__get_packed_size
                     (const Uenibstreamprotobuf__PHUplinkCarrierSCG   *message);
size_t uenibstreamprotobuf__ph__uplink_carrier_scg__pack
                     (const Uenibstreamprotobuf__PHUplinkCarrierSCG   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__ph__uplink_carrier_scg__pack_to_buffer
                     (const Uenibstreamprotobuf__PHUplinkCarrierSCG   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__PHUplinkCarrierSCG *
       uenibstreamprotobuf__ph__uplink_carrier_scg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__ph__uplink_carrier_scg__free_unpacked
                     (Uenibstreamprotobuf__PHUplinkCarrierSCG *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__MeasConfigSN methods */
void   uenibstreamprotobuf__meas_config_sn__init
                     (Uenibstreamprotobuf__MeasConfigSN         *message);
size_t uenibstreamprotobuf__meas_config_sn__get_packed_size
                     (const Uenibstreamprotobuf__MeasConfigSN   *message);
size_t uenibstreamprotobuf__meas_config_sn__pack
                     (const Uenibstreamprotobuf__MeasConfigSN   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__meas_config_sn__pack_to_buffer
                     (const Uenibstreamprotobuf__MeasConfigSN   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__MeasConfigSN *
       uenibstreamprotobuf__meas_config_sn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__meas_config_sn__free_unpacked
                     (Uenibstreamprotobuf__MeasConfigSN *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Uenibstreamprotobuf__CGConfig_Closure)
                 (const Uenibstreamprotobuf__CGConfig *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1_Closure)
                 (const Uenibstreamprotobuf__CGConfigCriticalExtensionsChoice1 *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__CGConfigIEs_Closure)
                 (const Uenibstreamprotobuf__CGConfigIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ConfigRestrictModReqSCG_Closure)
                 (const Uenibstreamprotobuf__ConfigRestrictModReqSCG *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__BandCombinationInfoSN_Closure)
                 (const Uenibstreamprotobuf__BandCombinationInfoSN *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__FRInfoList_Closure)
                 (const Uenibstreamprotobuf__FRInfoList *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__FRInfo_Closure)
                 (const Uenibstreamprotobuf__FRInfo *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__FRType_Closure)
                 (const Uenibstreamprotobuf__FRType *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__CandidateServingFreqListNR_Closure)
                 (const Uenibstreamprotobuf__CandidateServingFreqListNR *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__CGConfigV1540IEs_Closure)
                 (const Uenibstreamprotobuf__CGConfigV1540IEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ReportCGIRequest_Closure)
                 (const Uenibstreamprotobuf__ReportCGIRequest *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RequestedCellInfo_Closure)
                 (const Uenibstreamprotobuf__RequestedCellInfo *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__PHTypeListSCG_Closure)
                 (const Uenibstreamprotobuf__PHTypeListSCG *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__PHInfoSCG_Closure)
                 (const Uenibstreamprotobuf__PHInfoSCG *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__PHUplinkCarrierSCG_Closure)
                 (const Uenibstreamprotobuf__PHUplinkCarrierSCG *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__MeasConfigSN_Closure)
                 (const Uenibstreamprotobuf__MeasConfigSN *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uenibstreamprotobuf__cg__config__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__cg__config_critical_extensions_choice1__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__cg__config__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__config_restrict_mod_req_scg__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__band_combination_info_sn__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__fr__info_list__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__fr__info__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__fr__type__descriptor;
extern const ProtobufCEnumDescriptor    uenibstreamprotobuf__fr__type__value__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__candidate_serving_freq_list_nr__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__cg__config_v1540__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__report_cgi__request__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__requested_cell_info__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__ph__type_list_scg__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__ph__info_scg__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__ph__uplink_carrier_scg__descriptor;
extern const ProtobufCEnumDescriptor    uenibstreamprotobuf__ph__uplink_carrier_scg__ph__type1or3__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__meas_config_sn__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rrc_5fcg_5fconfig_2eproto__INCLUDED */
