/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rrc_reconfiguration_complete.proto */

#ifndef PROTOBUF_C_rrc_5freconfiguration_5fcomplete_2eproto__INCLUDED
#define PROTOBUF_C_rrc_5freconfiguration_5fcomplete_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "rrc_common_types.pb-c.h"

typedef struct _Uenibstreamprotobuf__RRCReconfigurationComplete Uenibstreamprotobuf__RRCReconfigurationComplete;
typedef struct _Uenibstreamprotobuf__RRCReconfigurationCompleteIEs Uenibstreamprotobuf__RRCReconfigurationCompleteIEs;
typedef struct _Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__CRITICAL_EXTENSIONS__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__CRITICAL_EXTENSIONS_RRC_RECONFIGURATION_COMPLETE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__CRITICAL_EXTENSIONS)
} Uenibstreamprotobuf__RRCReconfigurationComplete__CriticalExtensionsCase;

struct  _Uenibstreamprotobuf__RRCReconfigurationComplete
{
  ProtobufCMessage base;
  uint32_t rrc_transactionidentifier;
  Uenibstreamprotobuf__RRCReconfigurationComplete__CriticalExtensionsCase critical_extensions_case;
  union {
    Uenibstreamprotobuf__RRCReconfigurationCompleteIEs *rrcreconfigurationcomplete;
  };
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration_complete__descriptor) \
    , 0, UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__CRITICAL_EXTENSIONS__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__RRCReconfigurationCompleteIEs
{
  ProtobufCMessage base;
  Google__Protobuf__StringValue *latenoncriticalextension;
  Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs *noncriticalextension;
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration_complete__ies__descriptor) \
    , NULL, NULL }


struct  _Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__UplinkTxDirectCurrentList *uplinktxdirectcurrentlist;
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_COMPLETE_V1530__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__descriptor) \
    , NULL }


/* Uenibstreamprotobuf__RRCReconfigurationComplete methods */
void   uenibstreamprotobuf__rrcreconfiguration_complete__init
                     (Uenibstreamprotobuf__RRCReconfigurationComplete         *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationComplete   *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationComplete   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationComplete   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationComplete *
       uenibstreamprotobuf__rrcreconfiguration_complete__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration_complete__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationComplete *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RRCReconfigurationCompleteIEs methods */
void   uenibstreamprotobuf__rrcreconfiguration_complete__ies__init
                     (Uenibstreamprotobuf__RRCReconfigurationCompleteIEs         *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteIEs   *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__ies__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration_complete__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationCompleteIEs *
       uenibstreamprotobuf__rrcreconfiguration_complete__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration_complete__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationCompleteIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs methods */
void   uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__init
                     (Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs         *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs   *message);
size_t uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs *
       uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Uenibstreamprotobuf__RRCReconfigurationComplete_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationComplete *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RRCReconfigurationCompleteIEs_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationCompleteIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationCompleteV1530IEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration_complete__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration_complete__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration_complete_v1530__ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rrc_5freconfiguration_5fcomplete_2eproto__INCLUDED */
