/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rrc_reconfiguration.proto */

#ifndef PROTOBUF_C_rrc_5freconfiguration_2eproto__INCLUDED
#define PROTOBUF_C_rrc_5freconfiguration_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "common_types.pb-c.h"
#include "rrc_common_types.pb-c.h"
#include "rrc_sib.pb-c.h"
#include "rrc_system_information.pb-c.h"

typedef struct _Uenibstreamprotobuf__RRCReconfiguration Uenibstreamprotobuf__RRCReconfiguration;
typedef struct _Uenibstreamprotobuf__RRCReconfigurationIEs Uenibstreamprotobuf__RRCReconfigurationIEs;
typedef struct _Uenibstreamprotobuf__RRCReconfigurationV1530IEs Uenibstreamprotobuf__RRCReconfigurationV1530IEs;
typedef struct _Uenibstreamprotobuf__MasterKeyUpdate Uenibstreamprotobuf__MasterKeyUpdate;
typedef struct _Uenibstreamprotobuf__RRCReconfigurationV1540IEs Uenibstreamprotobuf__RRCReconfigurationV1540IEs;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__CRITICAL_EXTENSIONS__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__CRITICAL_EXTENSIONS_RRC_RECONFIGURATION = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__CRITICAL_EXTENSIONS)
} Uenibstreamprotobuf__RRCReconfiguration__CriticalExtensionsCase;

struct  _Uenibstreamprotobuf__RRCReconfiguration
{
  ProtobufCMessage base;
  uint32_t rrc_transactionidentifier;
  Uenibstreamprotobuf__RRCReconfiguration__CriticalExtensionsCase critical_extensions_case;
  union {
    Uenibstreamprotobuf__RRCReconfigurationIEs *rrcreconfiguration;
  };
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration__descriptor) \
    , 0, UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__CRITICAL_EXTENSIONS__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__RRCReconfigurationIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__RadioBearerConfig *radiobearerconfig;
  Uenibstreamprotobuf__CellGroupConfig *secondarycellgroup;
  Uenibstreamprotobuf__MeasConfig *measconfig;
  Google__Protobuf__StringValue *latenoncriticalextension;
  Uenibstreamprotobuf__RRCReconfigurationV1530IEs *noncriticalextension;
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration__ies__descriptor) \
    , NULL, NULL, NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__RRCReconfigurationV1530IEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__CellGroupConfig *mastercellgroup;
  Uenibstreamprotobuf__TrueOpt *fullconfig;
  size_t n_dedicatednas_messagelist;
  char **dedicatednas_messagelist;
  Uenibstreamprotobuf__MasterKeyUpdate *masterkeyupdate;
  Uenibstreamprotobuf__SIB1 *dedicatedsib1_delivery;
  Uenibstreamprotobuf__SystemInformation *dedicatedsysteminformationdelivery;
  Uenibstreamprotobuf__OtherConfig *otherconfig;
  Uenibstreamprotobuf__RRCReconfigurationV1540IEs *noncriticalextension;
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_V1530__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration_v1530__ies__descriptor) \
    , NULL, NULL, 0,NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__MasterKeyUpdate
{
  ProtobufCMessage base;
  protobuf_c_boolean keysetchangeindicator;
  uint32_t nexthopchainingcount;
  Google__Protobuf__StringValue *nas_container;
};
#define UENIBSTREAMPROTOBUF__MASTER_KEY_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__master_key_update__descriptor) \
    , 0, 0, NULL }


struct  _Uenibstreamprotobuf__RRCReconfigurationV1540IEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__OtherConfigV1540 *otherconfig_v1540;
};
#define UENIBSTREAMPROTOBUF__RRCRECONFIGURATION_V1540__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__rrcreconfiguration_v1540__ies__descriptor) \
    , NULL }


/* Uenibstreamprotobuf__RRCReconfiguration methods */
void   uenibstreamprotobuf__rrcreconfiguration__init
                     (Uenibstreamprotobuf__RRCReconfiguration         *message);
size_t uenibstreamprotobuf__rrcreconfiguration__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfiguration   *message);
size_t uenibstreamprotobuf__rrcreconfiguration__pack
                     (const Uenibstreamprotobuf__RRCReconfiguration   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfiguration   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfiguration *
       uenibstreamprotobuf__rrcreconfiguration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfiguration *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RRCReconfigurationIEs methods */
void   uenibstreamprotobuf__rrcreconfiguration__ies__init
                     (Uenibstreamprotobuf__RRCReconfigurationIEs         *message);
size_t uenibstreamprotobuf__rrcreconfiguration__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationIEs   *message);
size_t uenibstreamprotobuf__rrcreconfiguration__ies__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationIEs *
       uenibstreamprotobuf__rrcreconfiguration__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RRCReconfigurationV1530IEs methods */
void   uenibstreamprotobuf__rrcreconfiguration_v1530__ies__init
                     (Uenibstreamprotobuf__RRCReconfigurationV1530IEs         *message);
size_t uenibstreamprotobuf__rrcreconfiguration_v1530__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationV1530IEs   *message);
size_t uenibstreamprotobuf__rrcreconfiguration_v1530__ies__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationV1530IEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration_v1530__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationV1530IEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationV1530IEs *
       uenibstreamprotobuf__rrcreconfiguration_v1530__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration_v1530__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationV1530IEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__MasterKeyUpdate methods */
void   uenibstreamprotobuf__master_key_update__init
                     (Uenibstreamprotobuf__MasterKeyUpdate         *message);
size_t uenibstreamprotobuf__master_key_update__get_packed_size
                     (const Uenibstreamprotobuf__MasterKeyUpdate   *message);
size_t uenibstreamprotobuf__master_key_update__pack
                     (const Uenibstreamprotobuf__MasterKeyUpdate   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__master_key_update__pack_to_buffer
                     (const Uenibstreamprotobuf__MasterKeyUpdate   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__MasterKeyUpdate *
       uenibstreamprotobuf__master_key_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__master_key_update__free_unpacked
                     (Uenibstreamprotobuf__MasterKeyUpdate *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__RRCReconfigurationV1540IEs methods */
void   uenibstreamprotobuf__rrcreconfiguration_v1540__ies__init
                     (Uenibstreamprotobuf__RRCReconfigurationV1540IEs         *message);
size_t uenibstreamprotobuf__rrcreconfiguration_v1540__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCReconfigurationV1540IEs   *message);
size_t uenibstreamprotobuf__rrcreconfiguration_v1540__ies__pack
                     (const Uenibstreamprotobuf__RRCReconfigurationV1540IEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__rrcreconfiguration_v1540__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCReconfigurationV1540IEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__RRCReconfigurationV1540IEs *
       uenibstreamprotobuf__rrcreconfiguration_v1540__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__rrcreconfiguration_v1540__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCReconfigurationV1540IEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Uenibstreamprotobuf__RRCReconfiguration_Closure)
                 (const Uenibstreamprotobuf__RRCReconfiguration *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RRCReconfigurationIEs_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RRCReconfigurationV1530IEs_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationV1530IEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__MasterKeyUpdate_Closure)
                 (const Uenibstreamprotobuf__MasterKeyUpdate *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__RRCReconfigurationV1540IEs_Closure)
                 (const Uenibstreamprotobuf__RRCReconfigurationV1540IEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration_v1530__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__master_key_update__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__rrcreconfiguration_v1540__ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rrc_5freconfiguration_2eproto__INCLUDED */
