/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rrctransfer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rrctransfer.pb-c.h"
void   uenibstreamprotobuf__uenrmeasurement__ext_ies__init
                     (Uenibstreamprotobuf__UENRMeasurementExtIEs         *message)
{
  static const Uenibstreamprotobuf__UENRMeasurementExtIEs init_value = UENIBSTREAMPROTOBUF__UENRMEASUREMENT__EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__uenrmeasurement__ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__UENRMeasurementExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__uenrmeasurement__ext_ies__pack
                     (const Uenibstreamprotobuf__UENRMeasurementExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__uenrmeasurement__ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__UENRMeasurementExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__UENRMeasurementExtIEs *
       uenibstreamprotobuf__uenrmeasurement__ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__UENRMeasurementExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__uenrmeasurement__ext_ies__free_unpacked
                     (Uenibstreamprotobuf__UENRMeasurementExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__uenrmeasurement__init
                     (Uenibstreamprotobuf__UENRMeasurement         *message)
{
  static const Uenibstreamprotobuf__UENRMeasurement init_value = UENIBSTREAMPROTOBUF__UENRMEASUREMENT__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__uenrmeasurement__get_packed_size
                     (const Uenibstreamprotobuf__UENRMeasurement *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__uenrmeasurement__pack
                     (const Uenibstreamprotobuf__UENRMeasurement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__uenrmeasurement__pack_to_buffer
                     (const Uenibstreamprotobuf__UENRMeasurement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__UENRMeasurement *
       uenibstreamprotobuf__uenrmeasurement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__UENRMeasurement *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__uenrmeasurement__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__uenrmeasurement__free_unpacked
                     (Uenibstreamprotobuf__UENRMeasurement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__uenrmeasurement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__split_srb__ext_ies__init
                     (Uenibstreamprotobuf__SplitSRBExtIEs         *message)
{
  static const Uenibstreamprotobuf__SplitSRBExtIEs init_value = UENIBSTREAMPROTOBUF__SPLIT_SRB__EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__split_srb__ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__SplitSRBExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__split_srb__ext_ies__pack
                     (const Uenibstreamprotobuf__SplitSRBExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__split_srb__ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__SplitSRBExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__SplitSRBExtIEs *
       uenibstreamprotobuf__split_srb__ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__SplitSRBExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__split_srb__ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__split_srb__ext_ies__free_unpacked
                     (Uenibstreamprotobuf__SplitSRBExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__delivery_status__ext_ies__init
                     (Uenibstreamprotobuf__DeliveryStatusExtIEs         *message)
{
  static const Uenibstreamprotobuf__DeliveryStatusExtIEs init_value = UENIBSTREAMPROTOBUF__DELIVERY_STATUS__EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__delivery_status__ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__DeliveryStatusExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__delivery_status__ext_ies__pack
                     (const Uenibstreamprotobuf__DeliveryStatusExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__delivery_status__ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__DeliveryStatusExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__DeliveryStatusExtIEs *
       uenibstreamprotobuf__delivery_status__ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__DeliveryStatusExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__delivery_status__ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__delivery_status__ext_ies__free_unpacked
                     (Uenibstreamprotobuf__DeliveryStatusExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__delivery_status__init
                     (Uenibstreamprotobuf__DeliveryStatus         *message)
{
  static const Uenibstreamprotobuf__DeliveryStatus init_value = UENIBSTREAMPROTOBUF__DELIVERY_STATUS__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__delivery_status__get_packed_size
                     (const Uenibstreamprotobuf__DeliveryStatus *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__delivery_status__pack
                     (const Uenibstreamprotobuf__DeliveryStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__delivery_status__pack_to_buffer
                     (const Uenibstreamprotobuf__DeliveryStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__DeliveryStatus *
       uenibstreamprotobuf__delivery_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__DeliveryStatus *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__delivery_status__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__delivery_status__free_unpacked
                     (Uenibstreamprotobuf__DeliveryStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__delivery_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__split_srb__init
                     (Uenibstreamprotobuf__SplitSRB         *message)
{
  static const Uenibstreamprotobuf__SplitSRB init_value = UENIBSTREAMPROTOBUF__SPLIT_SRB__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__split_srb__get_packed_size
                     (const Uenibstreamprotobuf__SplitSRB *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__split_srb__pack
                     (const Uenibstreamprotobuf__SplitSRB *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__split_srb__pack_to_buffer
                     (const Uenibstreamprotobuf__SplitSRB *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__SplitSRB *
       uenibstreamprotobuf__split_srb__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__SplitSRB *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__split_srb__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__split_srb__free_unpacked
                     (Uenibstreamprotobuf__SplitSRB *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__split_srb__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__rrctransfer__ies__init
                     (Uenibstreamprotobuf__RRCTransferIEs         *message)
{
  static const Uenibstreamprotobuf__RRCTransferIEs init_value = UENIBSTREAMPROTOBUF__RRCTRANSFER__IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__rrctransfer__ies__get_packed_size
                     (const Uenibstreamprotobuf__RRCTransferIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__rrctransfer__ies__pack
                     (const Uenibstreamprotobuf__RRCTransferIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__rrctransfer__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCTransferIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__RRCTransferIEs *
       uenibstreamprotobuf__rrctransfer__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__RRCTransferIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__rrctransfer__ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__rrctransfer__ies__free_unpacked
                     (Uenibstreamprotobuf__RRCTransferIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__rrctransfer__init
                     (Uenibstreamprotobuf__RRCTransfer         *message)
{
  static const Uenibstreamprotobuf__RRCTransfer init_value = UENIBSTREAMPROTOBUF__RRCTRANSFER__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__rrctransfer__get_packed_size
                     (const Uenibstreamprotobuf__RRCTransfer *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__rrctransfer__pack
                     (const Uenibstreamprotobuf__RRCTransfer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__rrctransfer__pack_to_buffer
                     (const Uenibstreamprotobuf__RRCTransfer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__RRCTransfer *
       uenibstreamprotobuf__rrctransfer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__RRCTransfer *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__rrctransfer__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__rrctransfer__free_unpacked
                     (Uenibstreamprotobuf__RRCTransfer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__rrctransfer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define uenibstreamprotobuf__uenrmeasurement__ext_ies__field_descriptors NULL
#define uenibstreamprotobuf__uenrmeasurement__ext_ies__field_indices_by_name NULL
#define uenibstreamprotobuf__uenrmeasurement__ext_ies__number_ranges NULL
const ProtobufCMessageDescriptor uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.UENRMeasurement_ExtIEs",
  "UENRMeasurementExtIEs",
  "Uenibstreamprotobuf__UENRMeasurementExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__UENRMeasurementExtIEs),
  0,
  uenibstreamprotobuf__uenrmeasurement__ext_ies__field_descriptors,
  uenibstreamprotobuf__uenrmeasurement__ext_ies__field_indices_by_name,
  0,  uenibstreamprotobuf__uenrmeasurement__ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__uenrmeasurement__ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__uenrmeasurement__field_descriptors[2] =
{
  {
    "uENRMeasurements",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__UENRMeasurement, uenrmeasurements),
    &uenibstreamprotobuf__rrccontainer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__UENRMeasurement, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__UENRMeasurement, ie_extensions),
    &uenibstreamprotobuf__uenrmeasurement__ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__uenrmeasurement__field_indices_by_name[] = {
  1,   /* field[1] = iE_Extensions */
  0,   /* field[0] = uENRMeasurements */
};
static const ProtobufCIntRange uenibstreamprotobuf__uenrmeasurement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__uenrmeasurement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.UENRMeasurement",
  "UENRMeasurement",
  "Uenibstreamprotobuf__UENRMeasurement",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__UENRMeasurement),
  2,
  uenibstreamprotobuf__uenrmeasurement__field_descriptors,
  uenibstreamprotobuf__uenrmeasurement__field_indices_by_name,
  1,  uenibstreamprotobuf__uenrmeasurement__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__uenrmeasurement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define uenibstreamprotobuf__split_srb__ext_ies__field_descriptors NULL
#define uenibstreamprotobuf__split_srb__ext_ies__field_indices_by_name NULL
#define uenibstreamprotobuf__split_srb__ext_ies__number_ranges NULL
const ProtobufCMessageDescriptor uenibstreamprotobuf__split_srb__ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.SplitSRB_ExtIEs",
  "SplitSRBExtIEs",
  "Uenibstreamprotobuf__SplitSRBExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__SplitSRBExtIEs),
  0,
  uenibstreamprotobuf__split_srb__ext_ies__field_descriptors,
  uenibstreamprotobuf__split_srb__ext_ies__field_indices_by_name,
  0,  uenibstreamprotobuf__split_srb__ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__split_srb__ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define uenibstreamprotobuf__delivery_status__ext_ies__field_descriptors NULL
#define uenibstreamprotobuf__delivery_status__ext_ies__field_indices_by_name NULL
#define uenibstreamprotobuf__delivery_status__ext_ies__number_ranges NULL
const ProtobufCMessageDescriptor uenibstreamprotobuf__delivery_status__ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.DeliveryStatus_ExtIEs",
  "DeliveryStatusExtIEs",
  "Uenibstreamprotobuf__DeliveryStatusExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__DeliveryStatusExtIEs),
  0,
  uenibstreamprotobuf__delivery_status__ext_ies__field_descriptors,
  uenibstreamprotobuf__delivery_status__ext_ies__field_indices_by_name,
  0,  uenibstreamprotobuf__delivery_status__ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__delivery_status__ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__delivery_status__field_descriptors[2] =
{
  {
    "highestSuccessDeliveredPDCPSN",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__DeliveryStatus, highestsuccessdeliveredpdcpsn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__DeliveryStatus, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__DeliveryStatus, ie_extensions),
    &uenibstreamprotobuf__delivery_status__ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__delivery_status__field_indices_by_name[] = {
  0,   /* field[0] = highestSuccessDeliveredPDCPSN */
  1,   /* field[1] = iE_Extensions */
};
static const ProtobufCIntRange uenibstreamprotobuf__delivery_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__delivery_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.DeliveryStatus",
  "DeliveryStatus",
  "Uenibstreamprotobuf__DeliveryStatus",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__DeliveryStatus),
  2,
  uenibstreamprotobuf__delivery_status__field_descriptors,
  uenibstreamprotobuf__delivery_status__field_indices_by_name,
  1,  uenibstreamprotobuf__delivery_status__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__delivery_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue uenibstreamprotobuf__split_srb__srbtype__enum_values_by_number[3] =
{
  { "protobuf_unspecified", "UENIBSTREAMPROTOBUF__SPLIT_SRB__SRBTYPE__protobuf_unspecified", 0 },
  { "srb1", "UENIBSTREAMPROTOBUF__SPLIT_SRB__SRBTYPE__srb1", 1 },
  { "srb2", "UENIBSTREAMPROTOBUF__SPLIT_SRB__SRBTYPE__srb2", 2 },
};
static const ProtobufCIntRange uenibstreamprotobuf__split_srb__srbtype__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex uenibstreamprotobuf__split_srb__srbtype__enum_values_by_name[3] =
{
  { "protobuf_unspecified", 0 },
  { "srb1", 1 },
  { "srb2", 2 },
};
const ProtobufCEnumDescriptor uenibstreamprotobuf__split_srb__srbtype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.SplitSRB.SRBType",
  "SRBType",
  "Uenibstreamprotobuf__SplitSRB__SRBType",
  "uenibstreamprotobuf",
  3,
  uenibstreamprotobuf__split_srb__srbtype__enum_values_by_number,
  3,
  uenibstreamprotobuf__split_srb__srbtype__enum_values_by_name,
  1,
  uenibstreamprotobuf__split_srb__srbtype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__split_srb__field_descriptors[4] =
{
  {
    "rrcContainer",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SplitSRB, rrccontainer),
    &uenibstreamprotobuf__rrccontainer__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srbType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SplitSRB, srbtype),
    &uenibstreamprotobuf__split_srb__srbtype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deliveryStatus",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SplitSRB, deliverystatus),
    &uenibstreamprotobuf__delivery_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__SplitSRB, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__SplitSRB, ie_extensions),
    &uenibstreamprotobuf__split_srb__ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__split_srb__field_indices_by_name[] = {
  2,   /* field[2] = deliveryStatus */
  3,   /* field[3] = iE_Extensions */
  0,   /* field[0] = rrcContainer */
  1,   /* field[1] = srbType */
};
static const ProtobufCIntRange uenibstreamprotobuf__split_srb__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__split_srb__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.SplitSRB",
  "SplitSRB",
  "Uenibstreamprotobuf__SplitSRB",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__SplitSRB),
  4,
  uenibstreamprotobuf__split_srb__field_descriptors,
  uenibstreamprotobuf__split_srb__field_indices_by_name,
  1,  uenibstreamprotobuf__split_srb__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__split_srb__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__rrctransfer__ies__field_descriptors[5] =
{
  {
    "id_MeNB_UE_X2AP_ID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransferIEs, id_menb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SgNB_UE_X2AP_ID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransferIEs, id_sgnb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SplitSRB",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransferIEs, id_splitsrb),
    &uenibstreamprotobuf__split_srb__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_UENRMeasurement",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransferIEs, id_uenrmeasurement),
    &uenibstreamprotobuf__uenrmeasurement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_MeNB_UE_X2AP_ID_Extension",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransferIEs, id_menb_ue_x2ap_id_extension),
    &google__protobuf__uint32_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__rrctransfer__ies__field_indices_by_name[] = {
  0,   /* field[0] = id_MeNB_UE_X2AP_ID */
  4,   /* field[4] = id_MeNB_UE_X2AP_ID_Extension */
  1,   /* field[1] = id_SgNB_UE_X2AP_ID */
  2,   /* field[2] = id_SplitSRB */
  3,   /* field[3] = id_UENRMeasurement */
};
static const ProtobufCIntRange uenibstreamprotobuf__rrctransfer__ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__rrctransfer__ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.RRCTransfer_IEs",
  "RRCTransferIEs",
  "Uenibstreamprotobuf__RRCTransferIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__RRCTransferIEs),
  5,
  uenibstreamprotobuf__rrctransfer__ies__field_descriptors,
  uenibstreamprotobuf__rrctransfer__ies__field_indices_by_name,
  1,  uenibstreamprotobuf__rrctransfer__ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__rrctransfer__ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__rrctransfer__field_descriptors[1] =
{
  {
    "rrcTransfer_IEs",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__RRCTransfer, rrctransfer_ies),
    &uenibstreamprotobuf__rrctransfer__ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__rrctransfer__field_indices_by_name[] = {
  0,   /* field[0] = rrcTransfer_IEs */
};
static const ProtobufCIntRange uenibstreamprotobuf__rrctransfer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__rrctransfer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.RRCTransfer",
  "RRCTransfer",
  "Uenibstreamprotobuf__RRCTransfer",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__RRCTransfer),
  1,
  uenibstreamprotobuf__rrctransfer__field_descriptors,
  uenibstreamprotobuf__rrctransfer__field_indices_by_name,
  1,  uenibstreamprotobuf__rrctransfer__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__rrctransfer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
