/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_modification_request.proto */

#ifndef PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "x2ap_common_types.pb-c.h"
#include "common_types.pb-c.h"
#include "error_cause.pb-c.h"
#include "rrc_cg_config_info.pb-c.h"

typedef struct _Uenibstreamprotobuf__SgNBModificationRequest Uenibstreamprotobuf__SgNBModificationRequest;
typedef struct _Uenibstreamprotobuf__SgNBModificationRequestIEs Uenibstreamprotobuf__SgNBModificationRequestIEs;
typedef struct _Uenibstreamprotobuf__UEContextInformationSgNBModReq Uenibstreamprotobuf__UEContextInformationSgNBModReq;
typedef struct _Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent;
typedef struct _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs;


/* --- enums --- */


/* --- messages --- */

struct  _Uenibstreamprotobuf__SgNBModificationRequest
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__SgNBModificationRequestIEs *protocolies;
};
#define UENIBSTREAMPROTOBUF__SG_NBMODIFICATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__sg_nbmodification_request__descriptor) \
    , NULL }


struct  _Uenibstreamprotobuf__SgNBModificationRequestIEs
{
  ProtobufCMessage base;
  uint32_t id_menb_ue_x2ap_id;
  uint32_t id_sgnb_ue_x2ap_id;
  Uenibstreamprotobuf__Cause *id_cause;
  Google__Protobuf__StringValue *id_selectedplmn;
  Uenibstreamprotobuf__HandoverRestrictionList *id_handoverrestrictionlist;
  Uenibstreamprotobuf__TrueOpt *id_scgconfigurationquery;
  Uenibstreamprotobuf__UEContextInformationSgNBModReq *id_ue_contextinformation_sgnbmodreq;
  /*
   *The content of id_MeNBtoSgNBContainer has been specified in 3GPP 38.331 to be CG-ConfigInfo.
   */
  Uenibstreamprotobuf__CGConfigInfo *id_menbtosgnbcontainer;
  Google__Protobuf__UInt32Value *id_menb_ue_x2ap_id_extension;
  Uenibstreamprotobuf__MeNBResourceCoordinationInformation *id_menbresourcecoordinationinformation;
  Uenibstreamprotobuf__SplitSRBs *id_requestedsplitsrbs;
  Uenibstreamprotobuf__SplitSRBs *id_requestedsplitsrbsrelease;
};
#define UENIBSTREAMPROTOBUF__SG_NBMODIFICATION_REQUEST__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__sg_nbmodification_request__ies__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__UEContextInformationSgNBModReq
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__NRUESecurityCapabilities *nrue_securitycapabilities;
  Google__Protobuf__StringValue *sgnb_securitykey;
  Uenibstreamprotobuf__UEAggregateMaximumBitRate *sgnbueaggregatemaximumbitrate;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList *e_rabs_tobeadded;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList *e_rabs_tobemodified;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList *e_rabs_tobereleased;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__UE__CONTEXT_INFORMATION__SG_NBMOD_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__ue__context_information__sg_nbmod_req__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs
{
  ProtobufCMessage base;
  Google__Protobuf__UInt32Value *id_subscriberprofileidforrfp;
};
#define UENIBSTREAMPROTOBUF__UE__CONTEXT_INFORMATION_SG_NBMOD_REQ_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__descriptor) \
    , NULL }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs **items;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem *id_e_rabs_tobeadded_sgnbmodreq_item;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 4,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem__ResourceConfigurationCase;

struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  uint32_t drb_id;
  Uenibstreamprotobuf__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs **ie_extensions;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__descriptor) \
    , 0, 0, NULL, 0,NULL, UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABLevelQoSParameters *full_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__GBRQosInformation *max_mn_admit_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__DLForwarding *dl_forwarding;
  Uenibstreamprotobuf__GTPtunnelEndpoint *menb_dl_gtp_teidatmcg;
  Uenibstreamprotobuf__GTPtunnelEndpoint *s1_ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__RLCMode *id_rlcmode_transferred;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
    , NULL }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABLevelQoSParameters *requested_scg_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__GTPtunnelEndpoint *menb_ul_gtp_teidatpdcp;
  Uenibstreamprotobuf__GTPtunnelEndpoint *secondary_menb_ul_gtp_teidatpdcp;
  Uenibstreamprotobuf__RLCMode *rlc_mode;
  Uenibstreamprotobuf__ULConfiguration *ul_configuration;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__PDCPSnLength *id_ulpdcpsnlength;
  Uenibstreamprotobuf__PDCPSnLength *id_dlpdcpsnlength;
  Uenibstreamprotobuf__DuplicationActivation *id_duplicationactivation;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
    , NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs **items;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem *id_e_rabs_tobemodified_sgnbmodreq_item;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 3,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem__ResourceConfigurationCase;

struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  Uenibstreamprotobuf__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs **ie_extensions;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__descriptor) \
    , 0, NULL, 0,NULL, UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABLevelQoSParameters *full_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__GBRQosInformation *max_mn_admit_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__GTPtunnelEndpoint *menb_dl_gtp_teidatmcg;
  Uenibstreamprotobuf__GTPtunnelEndpoint *s1_ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__RLCStatus *id_rlc_status;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
    , NULL }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABLevelQoSParameters *requested_scg_e_rab_level_qos_parameters;
  Uenibstreamprotobuf__GTPtunnelEndpoint *menb_ul_gtp_teidatpdcp;
  Uenibstreamprotobuf__ULConfiguration *ul_configuration;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , NULL, NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__PDCPSnLength *id_ulpdcpsnlength;
  Uenibstreamprotobuf__PDCPSnLength *id_dlpdcpsnlength;
  Uenibstreamprotobuf__GTPtunnelEndpoint *id_secondarymenbulgtpteidatpdcp;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
    , NULL, NULL, NULL }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs **items;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem *id_e_rabs_tobereleased_sgnbmodreq_item;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 3,
  UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem__ResourceConfigurationCase;

struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  Uenibstreamprotobuf__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs **ie_extensions;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__descriptor) \
    , 0, NULL, 0,NULL, UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  Uenibstreamprotobuf__GTPtunnelEndpoint *dl_gtptunnelendpoint;
  Uenibstreamprotobuf__GTPtunnelEndpoint *ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
     }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  size_t n_ie_extensions;
  Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , 0,NULL }


struct  _Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
};
#define UENIBSTREAMPROTOBUF__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
     }


/* Uenibstreamprotobuf__SgNBModificationRequest methods */
void   uenibstreamprotobuf__sg_nbmodification_request__init
                     (Uenibstreamprotobuf__SgNBModificationRequest         *message);
size_t uenibstreamprotobuf__sg_nbmodification_request__get_packed_size
                     (const Uenibstreamprotobuf__SgNBModificationRequest   *message);
size_t uenibstreamprotobuf__sg_nbmodification_request__pack
                     (const Uenibstreamprotobuf__SgNBModificationRequest   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__sg_nbmodification_request__pack_to_buffer
                     (const Uenibstreamprotobuf__SgNBModificationRequest   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__SgNBModificationRequest *
       uenibstreamprotobuf__sg_nbmodification_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__sg_nbmodification_request__free_unpacked
                     (Uenibstreamprotobuf__SgNBModificationRequest *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__SgNBModificationRequestIEs methods */
void   uenibstreamprotobuf__sg_nbmodification_request__ies__init
                     (Uenibstreamprotobuf__SgNBModificationRequestIEs         *message);
size_t uenibstreamprotobuf__sg_nbmodification_request__ies__get_packed_size
                     (const Uenibstreamprotobuf__SgNBModificationRequestIEs   *message);
size_t uenibstreamprotobuf__sg_nbmodification_request__ies__pack
                     (const Uenibstreamprotobuf__SgNBModificationRequestIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__sg_nbmodification_request__ies__pack_to_buffer
                     (const Uenibstreamprotobuf__SgNBModificationRequestIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__SgNBModificationRequestIEs *
       uenibstreamprotobuf__sg_nbmodification_request__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__sg_nbmodification_request__ies__free_unpacked
                     (Uenibstreamprotobuf__SgNBModificationRequestIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__UEContextInformationSgNBModReq methods */
void   uenibstreamprotobuf__ue__context_information__sg_nbmod_req__init
                     (Uenibstreamprotobuf__UEContextInformationSgNBModReq         *message);
size_t uenibstreamprotobuf__ue__context_information__sg_nbmod_req__get_packed_size
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReq   *message);
size_t uenibstreamprotobuf__ue__context_information__sg_nbmod_req__pack
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReq   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__ue__context_information__sg_nbmod_req__pack_to_buffer
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReq   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__UEContextInformationSgNBModReq *
       uenibstreamprotobuf__ue__context_information__sg_nbmod_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__ue__context_information__sg_nbmod_req__free_unpacked
                     (Uenibstreamprotobuf__UEContextInformationSgNBModReq *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs methods */
void   uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__init
                     (Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs         *message);
size_t uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs   *message);
size_t uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__pack
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs *
       uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Uenibstreamprotobuf__SgNBModificationRequest_Closure)
                 (const Uenibstreamprotobuf__SgNBModificationRequest *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__SgNBModificationRequestIEs_Closure)
                 (const Uenibstreamprotobuf__SgNBModificationRequestIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__UEContextInformationSgNBModReq_Closure)
                 (const Uenibstreamprotobuf__UEContextInformationSgNBModReq *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs_Closure)
                 (const Uenibstreamprotobuf__UEContextInformationSgNBModReqExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqList *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqList *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqList *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const Uenibstreamprotobuf__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uenibstreamprotobuf__sg_nbmodification_request__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__sg_nbmodification_request__ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__ue__context_information__sg_nbmod_req__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__ue__context_information_sg_nbmod_req_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED */
