/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_addition_request_acknowledge.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sgnb_addition_request_acknowledge.pb-c.h"
void   uenibstreamprotobuf__sg_nbaddition_request_acknowledge__init
                     (Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge         *message)
{
  static const Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge init_value = UENIBSTREAMPROTOBUF__SG_NBADDITION_REQUEST_ACKNOWLEDGE__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__sg_nbaddition_request_acknowledge__get_packed_size
                     (const Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__sg_nbaddition_request_acknowledge__pack
                     (const Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__sg_nbaddition_request_acknowledge__pack_to_buffer
                     (const Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *
       uenibstreamprotobuf__sg_nbaddition_request_acknowledge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__sg_nbaddition_request_acknowledge__free_unpacked
                     (Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK_LIST__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK__ITEM__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__init
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs         *message)
{
  static const Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs init_value = UENIBSTREAMPROTOBUF__E__RABS__TO_BE_ADDED__SG_NBADD_REQ_ACK__ITEM_EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *
       uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK__SG_NBPDCPPRESENT__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK__SG_NBPDCPPRESENT_EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK__SG_NBPDCPNOTPRESENT__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__init
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs         *message)
{
  static const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs init_value = UENIBSTREAMPROTOBUF__E__RABS__ADMITTED__TO_BE_ADDED__SG_NBADD_REQ_ACK__SG_NBPDCPNOTPRESENT_EXT_IES__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__pack
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *
       uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor uenibstreamprotobuf__sg_nbaddition_request_acknowledge__field_descriptors[10] =
{
  {
    "id_MeNB_UE_X2AP_ID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_menb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SgNB_UE_X2AP_ID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_sgnb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_e_rabs_admitted_tobeadded_sgnbaddreqacklist),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_E_RABs_NotAdmitted_List",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_e_rabs_notadmitted_list),
    &uenibstreamprotobuf__e__rab__list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SgNBtoMeNBContainer",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_sgnbtomenbcontainer),
    &uenibstreamprotobuf__cg__config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_CriticalityDiagnostics",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_criticalitydiagnostics),
    &uenibstreamprotobuf__criticality_diagnostics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_MeNB_UE_X2AP_ID_Extension",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_menb_ue_x2ap_id_extension),
    &google__protobuf__uint32_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_AdmittedSplitSRBs",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_admittedsplitsrbs),
    &uenibstreamprotobuf__split_srbs__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SgNBResourceCoordinationInformation",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_sgnbresourcecoordinationinformation),
    &uenibstreamprotobuf__sg_nbresource_coordination_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_RRCConfigIndication",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge, id_rrcconfigindication),
    &uenibstreamprotobuf__rrc__config__ind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__sg_nbaddition_request_acknowledge__field_indices_by_name[] = {
  7,   /* field[7] = id_AdmittedSplitSRBs */
  5,   /* field[5] = id_CriticalityDiagnostics */
  2,   /* field[2] = id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList */
  3,   /* field[3] = id_E_RABs_NotAdmitted_List */
  0,   /* field[0] = id_MeNB_UE_X2AP_ID */
  6,   /* field[6] = id_MeNB_UE_X2AP_ID_Extension */
  9,   /* field[9] = id_RRCConfigIndication */
  8,   /* field[8] = id_SgNBResourceCoordinationInformation */
  1,   /* field[1] = id_SgNB_UE_X2AP_ID */
  4,   /* field[4] = id_SgNBtoMeNBContainer */
};
static const ProtobufCIntRange uenibstreamprotobuf__sg_nbaddition_request_acknowledge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__sg_nbaddition_request_acknowledge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.SgNBAdditionRequestAcknowledge",
  "SgNBAdditionRequestAcknowledge",
  "Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__SgNBAdditionRequestAcknowledge),
  10,
  uenibstreamprotobuf__sg_nbaddition_request_acknowledge__field_descriptors,
  uenibstreamprotobuf__sg_nbaddition_request_acknowledge__field_indices_by_name,
  1,  uenibstreamprotobuf__sg_nbaddition_request_acknowledge__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__sg_nbaddition_request_acknowledge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__field_descriptors[1] =
{
  {
    "id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList, n_id_e_rabs_admitted_tobeadded_sgnbaddreqack_item),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList, id_e_rabs_admitted_tobeadded_sgnbaddreqack_item),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__field_indices_by_name[] = {
  0,   /* field[0] = id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList",
  "ERABsAdmittedToBeAddedSgNBAddReqAckList",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckList),
  1,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__field_descriptors[5] =
{
  {
    "e_RAB_ID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, e_rab_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "en_DC_ResourceConfiguration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, en_dc_resourceconfiguration),
    &uenibstreamprotobuf__en__dc__resource_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sgNBPDCPpresent",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, resource_configuration_case),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, sgnbpdcppresent),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sgNBPDCPnotpresent",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, resource_configuration_case),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, sgnbpdcpnotpresent),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem, ie_extensions),
    &uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__field_indices_by_name[] = {
  0,   /* field[0] = e_RAB_ID */
  1,   /* field[1] = en_DC_ResourceConfiguration */
  4,   /* field[4] = iE_Extensions */
  3,   /* field[3] = sgNBPDCPnotpresent */
  2,   /* field[2] = sgNBPDCPpresent */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item",
  "ERABsAdmittedToBeAddedSgNBAddReqAckItem",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckItem),
  5,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__field_descriptors NULL
#define uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__field_indices_by_name NULL
#define uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__number_ranges NULL
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs",
  "ERABsToBeAddedSgNBAddReqAckItemExtIEs",
  "Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsToBeAddedSgNBAddReqAckItemExtIEs),
  0,
  uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__field_descriptors,
  uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__field_indices_by_name,
  0,  uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__to_be_added__sg_nbadd_req_ack__item_ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__field_descriptors[8] =
{
  {
    "s1_DL_GTPtunnelEndpoint",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, s1_dl_gtptunnelendpoint),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sgNB_UL_GTP_TEIDatPDCP",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, sgnb_ul_gtp_teidatpdcp),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rlc_Mode",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, rlc_mode),
    &uenibstreamprotobuf__rlcmode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dL_Forwarding_GTPtunnelEndpoint",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, dl_forwarding_gtptunnelendpoint),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uL_Forwarding_GTPtunnelEndpoint",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, ul_forwarding_gtptunnelendpoint),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mCG_E_RAB_Level_QoS_Parameters",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, mcg_e_rab_level_qos_parameters),
    &uenibstreamprotobuf__e__rab__level__qo_s__parameters__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uL_Configuration",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, ul_configuration),
    &uenibstreamprotobuf__ulconfiguration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent, ie_extensions),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__field_indices_by_name[] = {
  3,   /* field[3] = dL_Forwarding_GTPtunnelEndpoint */
  7,   /* field[7] = iE_Extensions */
  5,   /* field[5] = mCG_E_RAB_Level_QoS_Parameters */
  2,   /* field[2] = rlc_Mode */
  0,   /* field[0] = s1_DL_GTPtunnelEndpoint */
  1,   /* field[1] = sgNB_UL_GTP_TEIDatPDCP */
  6,   /* field[6] = uL_Configuration */
  4,   /* field[4] = uL_Forwarding_GTPtunnelEndpoint */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent",
  "ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresent),
  8,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__field_descriptors[2] =
{
  {
    "id_uLpDCPSnLength",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs, id_ulpdcpsnlength),
    &uenibstreamprotobuf__pdcpsn_length__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_dLPDCPSnLength",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs, id_dlpdcpsnlength),
    &uenibstreamprotobuf__pdcpsn_length__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__field_indices_by_name[] = {
  1,   /* field[1] = id_dLPDCPSnLength */
  0,   /* field[0] = id_uLpDCPSnLength */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs",
  "ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPpresentExtIEs),
  2,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcppresent_ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__field_descriptors[3] =
{
  {
    "sgNB_DL_GTP_TEIDatSCG",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent, sgnb_dl_gtp_teidatscg),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secondary_sgNB_DL_GTP_TEIDatSCG",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent, secondary_sgnb_dl_gtp_teidatscg),
    &uenibstreamprotobuf__gtptunnel_endpoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iE_Extensions",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent, n_ie_extensions),
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent, ie_extensions),
    &uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__field_indices_by_name[] = {
  2,   /* field[2] = iE_Extensions */
  1,   /* field[1] = secondary_sgNB_DL_GTP_TEIDatSCG */
  0,   /* field[0] = sgNB_DL_GTP_TEIDatSCG */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent",
  "ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresent),
  3,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__field_descriptors[1] =
{
  {
    "lc_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs, lc_id),
    &google__protobuf__uint32_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__field_indices_by_name[] = {
  0,   /* field[0] = lc_id */
};
static const ProtobufCIntRange uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs",
  "ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs",
  "Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__ERABsAdmittedToBeAddedSgNBAddReqAckSgNBPDCPnotpresentExtIEs),
  1,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__field_descriptors,
  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__field_indices_by_name,
  1,  uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__e__rabs__admitted__to_be_added__sg_nbadd_req_ack__sg_nbpdcpnotpresent_ext_ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
