/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_addition_request_reject.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sgnb_addition_request_reject.pb-c.h"
void   uenibstreamprotobuf__sg_nbaddition_request_reject__init
                     (Uenibstreamprotobuf__SgNBAdditionRequestReject         *message)
{
  static const Uenibstreamprotobuf__SgNBAdditionRequestReject init_value = UENIBSTREAMPROTOBUF__SG_NBADDITION_REQUEST_REJECT__INIT;
  *message = init_value;
}
size_t uenibstreamprotobuf__sg_nbaddition_request_reject__get_packed_size
                     (const Uenibstreamprotobuf__SgNBAdditionRequestReject *message)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uenibstreamprotobuf__sg_nbaddition_request_reject__pack
                     (const Uenibstreamprotobuf__SgNBAdditionRequestReject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uenibstreamprotobuf__sg_nbaddition_request_reject__pack_to_buffer
                     (const Uenibstreamprotobuf__SgNBAdditionRequestReject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uenibstreamprotobuf__SgNBAdditionRequestReject *
       uenibstreamprotobuf__sg_nbaddition_request_reject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uenibstreamprotobuf__SgNBAdditionRequestReject *)
     protobuf_c_message_unpack (&uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor,
                                allocator, len, data);
}
void   uenibstreamprotobuf__sg_nbaddition_request_reject__free_unpacked
                     (Uenibstreamprotobuf__SgNBAdditionRequestReject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor uenibstreamprotobuf__sg_nbaddition_request_reject__field_descriptors[5] =
{
  {
    "id_MeNB_UE_X2AP_ID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestReject, id_menb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_SgNB_UE_X2AP_ID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestReject, id_sgnb_ue_x2ap_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_Cause",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestReject, id_cause),
    &uenibstreamprotobuf__cause__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_CriticalityDiagnostics",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestReject, id_criticalitydiagnostics),
    &uenibstreamprotobuf__criticality_diagnostics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id_MeNB_UE_X2AP_ID_Extension",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Uenibstreamprotobuf__SgNBAdditionRequestReject, id_menb_ue_x2ap_id_extension),
    &google__protobuf__uint32_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uenibstreamprotobuf__sg_nbaddition_request_reject__field_indices_by_name[] = {
  2,   /* field[2] = id_Cause */
  3,   /* field[3] = id_CriticalityDiagnostics */
  0,   /* field[0] = id_MeNB_UE_X2AP_ID */
  4,   /* field[4] = id_MeNB_UE_X2AP_ID_Extension */
  1,   /* field[1] = id_SgNB_UE_X2AP_ID */
};
static const ProtobufCIntRange uenibstreamprotobuf__sg_nbaddition_request_reject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor uenibstreamprotobuf__sg_nbaddition_request_reject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "uenibstreamprotobuf.SgNBAdditionRequestReject",
  "SgNBAdditionRequestReject",
  "Uenibstreamprotobuf__SgNBAdditionRequestReject",
  "uenibstreamprotobuf",
  sizeof(Uenibstreamprotobuf__SgNBAdditionRequestReject),
  5,
  uenibstreamprotobuf__sg_nbaddition_request_reject__field_descriptors,
  uenibstreamprotobuf__sg_nbaddition_request_reject__field_indices_by_name,
  1,  uenibstreamprotobuf__sg_nbaddition_request_reject__number_ranges,
  (ProtobufCMessageInit) uenibstreamprotobuf__sg_nbaddition_request_reject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
